### ISSUE TITLE
[Bug] Autolink patterns don't work when Translate plugin is enabled

### ISSUE THREAD

**Issue by meskill** [necauqua/obsidian-page-properties#4]
If the [Translate plugin](https://github.com/Fevol/obsidian-translate) is enabled then links from pattern (github, wiki etc) point to wrong urls like `https://github.com/%7B0%7D`

**Comment by necauqua** [comment]
Issue comes from the translator plugin, they are doing something pretty dumb which breaks everyones code, the fix has to come from them

**Comment by necauqua** [comment]
The `%7B0%7D` part is just url-encoded `{0}` from the link patterns, the translator plugin changes how the String.format call works _for the entire application_ so that instead of replacing `{0}`, `{1}` etc it only replaces consecutive `{}`s

The funniest part is that the comment says 'make it like in python', while the full Python formatter _does_ support `{0}`, `{1}` etc as well as `{}` (for the obvious reason of if you want to reorder things).

Anyway, until they fix that you can change the autolink patterns to have `{}` instead of `{0}` :shrug:

**Comment by Fevol** [comment]
I'd really like to apologize for this absolutely brain-dead mistake I made. This was code I've left in and never ended up using. I either never ended looking at the function again, or didn't realize why keeping it in is a **_bad_** idea. I'll be taking a look at my entire code again, and try to prevent something like this ever happening again.

Thank you @meskill for detecting the problem, and pointing it out by creating this issue. I am immensely grateful.
Sorry @necauqua for any worries I might've caused.

**Comment by meskill** [comment]
I'm glad that is resolved. Thank you guys for your work!
